steps:

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/writer:branch-master \
    || true
  id: 'pull_writer'

- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/writer:$TAG_NAME',
      '-f', 'Dockerfile',
      '.',
    ]
  id: 'build_writer'
  waitFor: ['pull_writer']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker push gcr.io/$PROJECT_ID/writer:$TAG_NAME
  id: 'push_writer'
  waitFor: ['build_writer']

# 30 mins
timeout: 1800s
