version: '3'
services:
  writer:
    image: writer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    network_mode: "host"
    stdin_open: true
    command: ./run-local.sh