apiVersion: batch/v1
kind: Job
metadata:
  name: writer
spec:
  template:
    metadata:
      name: writer
    spec:
      containers:
      - image: gcr.io/writer-01/writer:v1.2.1
        env:
        - name: name
          value: value
        name: writer
      volumes:
      - name: secrets
        secret:
          secretName: writer-app-engine-account
      restartPolicy: Never
